server:
  port: 8081

spring:
  profiles:
    active: @profiles.active@
  application:
    name: cc-demo
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.host:127.0.0.1}:${nacos.port:8849}
        namespace: 9c67e952-4ba6-4ba3-9ecb-5f3b568fa56b
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: DEFAULT_GROUP
        file-extension: yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
