server:
  port: 8091

spring:
  application:
    name: cc-user
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cc-platform
    username: root
    password: Admin888
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.host:localhost}:${nacos.port:8848}
        #namespace: 9c67e952-4ba6-4ba3-9ecb-5f3b568fa56b
        namespace: ${nacos.namespace:9c67e952-4ba6-4ba3-9ecb-5f3b568fa56b}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs: ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

logging:
  file:
    path: .

hmacsha256key: asdfasdfasdfasdf1234123412341234