#server:
#  port: 8080
#
#
#spring:
#  application:
#    name: nacos-demo
##  config:
##    import: configcenter://192.168.1.106:8848
#  cloud:
#    nacos:
#      config:
#        server-addr: 192.168.1.106:8848
#        file-extension: yaml
#        group: DEFAULT_GROUP
#        namespace: test
#  config:
#    import:
#      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?refreshEnabled=true
#
##      config:
##        server-addr: 192.168.1.100:8848
##      discovery:
##        server-addr: 192.168.1.100:8848