server:
  port: 8080

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: 9d2f2e60-cce8-464b-bbcc-4b399adc91b7
  config:
    import: "optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}"
#
##      config:
##        server-addr: 192.168.1.100:8848
##      discovery:
##        server-addr: 192.168.1.100:8848