server:
  port: 8080

spring:
  application:
    name: security-demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: 12345
logging:
  file:
    path: .