server:
  port: 20418
  servlet:
    context-path: /alipay
spring:
  application:
    name: alipay-demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# 自定义配置项
org:
  monkey:
    cc:
      platform:
        pay:
          alipay:
            app-id: 9021000138668424
            private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDanNEVMTiUpYKSPnCY3ZXv3WBwJRKmUm9VwCkcoFYJEvYJLKqBOjyOB0NZxxeGzC3KYkLuzNeILCmgaignWdSkyOU8XTkKvgMsAjsrwM8rkNELCJ9mX7QoNuHN162L2+IIF4HehECZ9EqhonvMh/4+sBmgd5LUKJnD0U3/o0BBHGztzFITqjfmLgDBgjUBGiyo17TXW6v0AXpy10cAI3SFkiL+n0zX/Pa/TZaliJmeEc/sieGjHb2rpe5KOKMIuxGcNXeFe8HI8c4ZIxhNWslYhqfxyvTHq+pPRe9L0PuASbgfLeEgf5xNhar32IrJf3XXzDAQ9WM0vN4/Ef+8ZYBzAgMBAAECggEAJPkYs4jblOhZKPq+eFwhm6vJP65FdTPD+LDDQ0AqzOYUDoErZSfAThUUYv61D+tAY1YzE8g5O6Kcd7D8kYsz15rSil8J4rM4Ph0yfLfjUe7wK/mNW/cbtSFzFyk/BMRvegbfxA6CDoeuh5+/aFwnt9p4uxb+Eju7pc6kbnPhziD8gSMnEzOqZMNmWmUKId2ytTLeaKJCEId9riVsZQ20LPXMxjerkJeyd8M0EpEGo2Q+wDoZO5MMvjSreUK+wlaWIWhAWWozp2jmzfxHOHS3AwhIqrVxQqV1vvpBzH6lrw3ipLu5fvplJxQPdL/RzFEQH+O7ytmJP95i27YidUdnoQKBgQD3dyaGPblz/RWlAu7JmwEH1whaEdYXi/BBnpapT3djb8dBo+oFJtMEoVpGIQSyXGZT9oRlVb/KMpHss4NbEDgBXvIj+KD2XfEjrCe/WwmlmIYPbAva1qhmRZQAnQpfFeOysmyl6B6zlliIqiRFiHXt8qxuthEBOsyyhm3rk9ofJwKBgQDiJu1MMnKHqlLzfgMxl0BNT1NKPv5D39rw0rPasx46CvASUXWV2BM9m72kdIHX0YotDY9iHlYXSh0dEzFDDJ7z+DIxyoJbaN1qbaZTM6KLIpgFvsq+G7mw1a6WqxHyesK8qDJCdM0W38xBazEd5QwzJ9RgSmq1ddXezuIE7abj1QKBgDy/ax2ZGWV3w1B2n9etzVr3Vn2F02CEYb46CBIYB97JGcjrTA9nsHV6hoagpF6EgDosUePuYN5p+5h3mM9J8/WiMR7TcfAIr6FqKXe4CW41OvOeOmrGNyCkA+kCpAEjhnnfgvxXNvIu/hzOZ4kKLqjy4ZFr8FC09nr8tQ8XhHwRAoGARTcYxYtjFjaA8NkObS0XlxHCMiUZePiYb8BtH3BWvfj/BPw9esEJEoAKCL1HyB/vpF5UFfmm67XZNz7aguTn+U9rPWX3g7aSnbI1h510EBVkZc3BC3I84OxlZOOyuH3uAAOSbliFNI0GXLdL7xRdKYL1MwtToXoRHQJAlrWNsIkCgYAlykod3tbFdo9/VP+aMye6YFTUAphM3GxlTux+5pxrTGtHXtUa1hciqzHccvZvzAUOJh3fhx2BR1gcslFZGdAA/3s4y7MmkGd3rwZ9C1eUMioV2kf33RbLsO9MFvgJHXlddk17Z+cw8slKdH1GS8saIbNu4Hh8oq8XxzqIseLNWw==
            alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA122EAScaIXLzfmPYQOFsMx7RKud7tY+OfEchx+2vPzWZMM1Dpw/N72x8CWtzFB6jdIlFAZRlWWRgvdixfxWl3AQ5c12F3uz1+5iZIfeVANEB/YHlu7E3lZQ3uneAsKCZbv4e/Bf828JpqAUQVZfaF24SLPIyhrrpV5BAm/r56tRPUf6IIG5+UrmtJLuGdvvp81pBr8OEPkj6VskQLc1xptRJFp+lmegMgOIZ8EWmLfY6Cauhdyy9OxwNwkj30T01EcsVgadVzic76+EAx3sNYm4C7fMGfN8vfXsJf9kPRSwK48polMVVA/2upgru/6ou83FqnZXB8WBOTnT1TlX3JQIDAQAB
            notify-url: http://856gf5005iu6.vicp.fun/alipay/api/notify
            return-url: http://856gf5005iu6.vicp.fun/alipay/test/test/123