package org.monkey.sprinterhu.parcel.resp;

import com.alibaba.fastjson.JSONObject;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

/**
 * ParcelResult
 *
 * @author cc
 * @since 2024/6/11 11:48
 */
@Data
@XmlAccessorType(XmlAccessType.NONE)
public class ParcelResult {

    @XmlAttribute(name = "xmlns:b")
    private String xmlnsB;

    @ApiModelProperty(" Error code")
    @XmlElement(name = "b:ErrorCode")
    private String errorCode;

    @ApiModelProperty(" Original barcode, which was sent at the registration")
    @XmlElement(name = "b:OriginalBarCode")
    private String originalBarCode;

    @ApiModelProperty(" New barcode")
    @XmlElement(name = "b:NewBarCode")
    private String newBarCode;

    @ApiModelProperty(" Not used anymore")
    @XmlElement(name = "b:OriginalDirectPackageBarCode")
    private String originalDirectPackageBarCode;

    @ApiModelProperty(" New barcode of a physical parcel, if it had to be re-generated. Not used anymore")
    @XmlElement(name = "b:NewDirectPackageBarCode")
    private String newDirectPackageBarCode;

    @ApiModelProperty(" Shipment ID connected to the parcel, which is generated by the system. In case of PPP service, 1 ID is generated per ServiceType. In case of HD service each Parcel has a separated ID.")
    @XmlElement(name = "b:ShipmentID")
    private String shipmentID;

    @ApiModelProperty(" Route number of the delivery address. In case of HD: postal code –> route number, in case of PPP route from depot to PPP ")
    @XmlElement(name = "b:DirectionNumber")
    private String directionNumber;

    @ApiModelProperty(" Route number of pickup address (Only at HD service and return)")
    @XmlElement(name = "b:DirectionNumberSender")
    private String directionNumberSender;

    @ApiModelProperty(" Response from international call")
    @XmlElement(name = "b:ErrorMessageInternational")
    private String errorMessageInternational;

    @ApiModelProperty(" Delayed delivery. Not used anymore.")
    @XmlElement(name = "b:IsDelayedDelivery")
    private Boolean isDelayedDelivery;


    @Override
    public String toString() {
        return JSONObject.toJSONString(this);
    }
}
